### ISSUE TITLE
A stability problem, and a fix for it

### ISSUE THREAD

**Issue by wjaguar** [kitanokitsune/gtk2.24-win-static-library-builder#1]
All GTK+2 versions on Windows have a bug, mixing up two types of handles in one hashtable and crashing at a random moment when their values clash. I fixed it in my own GTK+2/Win64 package build, but was too lazy to submit the patch to MXE; still, there is no reason for you to suffer from this avoidable problem.

Here is the description, under "The Specifics" heading:
https://github.com/wjaguar/mtPaint/blob/master/gtk/README.w64
and here is the patch:
https://github.com/wjaguar/mtPaint/blob/master/gtk/gtk22429_1wj.patch

The relevant part is the changes to gdk/win32/gdkpixmap-win32.c

**Comment by kitanokitsune** [comment]
Thank you for the information. I merged your patch into v1.2.
